// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	MsgTest1
	MsgTest2
*/
package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgTest1 struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id    int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *MsgTest1) Reset()                    { *m = MsgTest1{} }
func (m *MsgTest1) String() string            { return proto.CompactTextString(m) }
func (*MsgTest1) ProtoMessage()               {}
func (*MsgTest1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MsgTest1) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgTest1) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgTest1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type MsgTest2 struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id    int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *MsgTest2) Reset()                    { *m = MsgTest2{} }
func (m *MsgTest2) String() string            { return proto.CompactTextString(m) }
func (*MsgTest2) ProtoMessage()               {}
func (*MsgTest2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MsgTest2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgTest2) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgTest2) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgTest1)(nil), "example.MsgTest1")
	proto.RegisterType((*MsgTest2)(nil), "example.MsgTest2")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x55,
	0x72, 0xe1, 0xe2, 0xf0, 0x2d, 0x4e, 0x0f, 0x49, 0x2d, 0x2e, 0x31, 0x14, 0x12, 0xe2, 0x62, 0xc9,
	0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xf8, 0xb8, 0x98,
	0x32, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x84, 0x44, 0xb8, 0x58,
	0x53, 0x73, 0x13, 0x33, 0x73, 0x24, 0x98, 0xc1, 0x8a, 0x20, 0x1c, 0x24, 0x53, 0x8c, 0xc8, 0x37,
	0x25, 0x89, 0x0d, 0xec, 0x36, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x88, 0x20, 0x3c,
	0xa9, 0x00, 0x00, 0x00,
}
